### ISSUE TITLE
Add HDT backend

### ISSUE THREAD

**Issue by pchampin** [pchampin/sophia_rs#21]
An implementation of [`graph::Graph`](https://docs.rs/sophia/0.3.0/sophia/graph/trait.Graph.html) using an [HDT](http://www.rdfhdt.org/) file as its underlying data would be nice.

Note that this would be a read-only graph, as HDT does not support updates.

**Comment by KonradHoeffner** [comment]
I am also interested in this, but there seem to be no fully functional and performant HDT library yet.
There is a prototype at <https://github.com/timplication/hdt-rs/> which I try to improve but I can't guarantee that I succeed with it as it is quite complex.

**Comment by pchampin** [comment]
Another option would be to make a wrapper around [libhdt](https://github.com/rdfhdt/hdt-cpp/tree/develop/libhdt)

**Comment by KonradHoeffner** [comment]
I've now spent some time with hdt-rs and the main problem seems to be the lack of the locate function, which translates URIs back into dictionary ids.
There is a function that materializes the complete knowledge base into triples but when testing it with a 1.7 GB hdt file converted from a 27 GB ntriples file, this didn't fit into 32 GB RAM and caused Linux to kill the program.
Using the Java code as a baseline (I'm not comfortable enough with C++), I've added the locate function into a fork at <https://github.com/konradhoeffner/hdt-rs>, however this currently only works when the string is first in a block in the dictionary section, I will try to fix this and then implement a graph:Graph implementation.
The question is where this implementation should go, probably best directly into hdt-rs but as a feature that is not selected by default so that users of the library that don't use sophia don't have an extra dependency, or what do you think?

Wrapping libhdt would also be an option but I think someone else would need to do this as I have no experience wrapping C++ libraries in Rust.

**Comment by pchampin** [comment]
> The question is where this implementation should go, probably best directly into hdt-rs but as a feature that is not selected by default so that users of the library that don't use sophia don't have an extra dependency, or what do you think?

I think it would be ok to put the Graph impl in a different crate... but if you choose to put it in hdt-rs, yes, it should probably be feature-gated.

**Comment by KonradHoeffner** [comment]
The tests are successful now but don't cover everything yet but I will try implementing a Sophia Graph and put that inside the hdt-rs fork just for testing right now and later I can move it into a separate crate.

**Comment by KonradHoeffner** [comment]
I got it to run like this:

```rust
      Box::new(
            hdt_reader
                .triples()
                .map(|(s, p, o)| {
                    StreamedTriple::by_value([
                        Term::<String>::from(s),
                        Term::<String>::from(p),
                        Term::<String>::from(o),
                    ])
                })
                .into_triple_source(),
```

However when printing the result, the term type seems to always be literal even though they should be IRIs:

```
Ok(StreamedTriple { _phantom: PhantomData, wrapped: [Literal(Literal { txt: "_:b1", kind: Dt(Iri { ns: "http://www.w3.org/2001/XMLSchema#", suffix: Some("string") }) }), Literal(Literal { txt: "http://www.w3.org/1999/02/22-rdf-syntax-ns#_1", kind: Dt(Iri { ns: "http://www.w3.org/2001/XMLSchema#", suffix: Some("string") }) }), Literal(Literal { txt: "http://data.semanticweb.org/person/barry-norton", kind: Dt(Iri { ns: "http://www.w3.org/2001/XMLSchema#", suffix: Some("string") }) })] })
```

**Comment by pchampin** [comment]
FTR, this "StreamedTriple" thing is a ugly hack that my long awaited "[big refactoring]" is meant to get rid of. Sorry you have to go through this...

What you need is a function that "understands" the HDT convention that:
* anything between `<>` is an IRI,
* anything between `""` is a literal
* anything starting with `_:` is a blank node (I guess)
and calls the appropriate [constructor of Term](https://docs.rs/sophia_term/latest/sophia_term/enum.Term.html#method.new_iri) (`new_iri` and following).

Note also that you may want to use `BoxTerm`, equivalent to `Term<Box<str>>`, instead of `Term<String>` (because you don't need the mutability of `String` in this context).

Note also that `BoxTerm` or `Term<String>` will allocate a copy of the str you get from the HDT, while ideally you could provide a term that *references* that str directly. This would probably be faster and leaner. Alas, this is super-hard to achieve with the `StreamedTriple` hack, and will be much easier in the next version. Hopefully, I will be able to push a pre-release  by the end of October...

In the meantime,if you want to make progress, you can continue with `BoxTerm` -- just be aware the performance will not be as good as they could be (and eventually will be).

[big refactoring]: https://perso.liris.cnrs.fr/pierre-antoine.champin/blog/2021/sophia-v0.7/#what-s-next

**Comment by KonradHoeffner** [comment]
Version 0.0.7 of the HDT Graph is now available at <https://crates.io/crates/hdt>.
Preliminary benchmarks comparing Sophia Fastgraph, Lightgraph and HDT Graph are available at <https://github.com/KonradHoeffner/sophia_benchmark/blob/master/benchmark_results.ipynb>.
I just forked <https://github.com/pchampin/sophia_benchmark/> and switched out the query part, the rest still has the old values.

**Comment by pchampin** [comment]
Thanks and kudos for this work.

Those results are quite counter intuitive (and therefore very intersting)!

Re. loading, I am amazed by the fact that HDT is faster, and by that order of magnitude. Intuitively, creating the HDT structures seems like more work... Or am I misunderstanding what you are measuring here? Are you loading from an N-Triples file, or from a file that is alteady in HDT format (in which case, I would better understand the results).

Re. querying, any idea why HDT is still slower?

**Comment by KonradHoeffner** [comment]
Thanks! Yes, the latter is true, I am converting the N-Triples files to HDT beforehand and only loading the existing HDT files because the library cannot create all of the HDT structures on its own but relies on loading existing HDT files. Also I think in a real-world scenario one would prefer to use HDT files anyways because they are much smaller.

As for querying, I think the main problem here is that the benchmark uses an ?PO pattern, which is one of the few ones that isn't fully optimized yet.
The current implementation uses the property index to first get all triple IDs (triples of integers) for the given property, then filters them by the given object and finally translates the triple IDs to strings.
This is faster than the Sophia Graph trait default implementation, which I think would also use triples_with_p() and then filter, but it would filter after the translation to string because it cannot know that HDT uses integer triples.
I could try parallelizing the filter operation as a quick optimization but I will also investigate if I can implement the fully optimized triples_with_po instead as this is planned anyways.

**Comment by KonradHoeffner** [comment]
I don't know why the memory used while allocating for the graph is so high for HDT even with the 10k triples file.
The plot shows around 200 MB (hard to see on the log scale) but when I use `/usr/bin/time -v` or heaptrack it shows much less.
Heaptrack reports 1 MB heap memory consumption.

**Comment by KonradHoeffner** [comment]
Added Jena back in and updated to version 4.6.1.
See <https://github.com/KonradHoeffner/sophia_benchmark/blob/master/benchmark_results.ipynb>.

**Comment by KonradHoeffner** [comment]
I started optimizing the triples_with_po method but there are still some bugs in the new implementation.
I consider comparing some other triple patterns as well, as ?PO should be one of the worst ones for HDT as the default data layout is S-P-O.

**Comment by KonradHoeffner** [comment]
P.S.: Loading could be made even faster by not creating the helper structures for the object- and predicate based access and then it would use less memory as well, but be even slower to query for triple patterns where this is necessary, probably similar to the FastGraph vs LightGraph split.

**Comment by KonradHoeffner** [comment]
https://github.com/KonradHoeffner/hdt/commit/d596b83107fd7c05320d77c8ae6a5e8736772f56 optimizes triples_with_po using binary search, I will recreate the benchmarks when I get to that machine the next time.

**Comment by KonradHoeffner** [comment]
There seems to be a lot of optimization potential:
![Uploading Screenshot from 2022-12-22 06-47-36.png…]()

Only 18% of the time is used to get the actual triple of integer IDs, while 49% of the time is taken to translate the IDs to strings and 28% for creating Sophia terms out of the strings.

Given that all results for a ?PO query share the same predicate and object, reusing those should be a big performance boost.
However that would mean using references or smartpointers instead of strings and those would need to be managed as well.

**Comment by KonradHoeffner** [comment]
After some optimization it looks much better now:
![Screenshot from 2022-12-22 13-09-46](https://user-images.githubusercontent.com/839577/209131686-3cd7fcef-60d9-4147-9bf2-a00d3b99aaa0.png)

However it is still nowhere near as fast as Sophia's FastGraph and I don't think I can achieve that kind of speed.

**Comment by pchampin** [comment]
Thanks a lot for all this work!

**Comment by KonradHoeffner** [comment]
> What you need is a function that "understands" the HDT convention that:
> 
> * anything between `<>` is an IRI,
> * anything between `""` is a literal
> * anything starting with `_:` is a blank node (I guess)
>   and calls the appropriate [constructor of Term](https://docs.rs/sophia_term/latest/sophia_term/enum.Term.html#method.new_iri) (`new_iri` and following).

Thanks! This function now exists as auto_term in https://github.com/KonradHoeffner/hdt/blob/main/src/hdt_graph.rs, however it is very slow because of the string matching so I'm in the process of getting rid of it wherever possible, for example in the predicate case where it is always a URI.

**Comment by KonradHoeffner** [comment]
> Note also that `BoxTerm` or `Term<String>` will allocate a copy of the str you get from the HDT, while ideally you could provide a term that _references_ that str directly. This would probably be faster and leaner.

I didn't understand Rust well enough at the time so I was a bit confused about why all those different datatypes were necessary but I finally understood it now and made the Hdt and HdtGraph structures generic as well so one can now choose between Box<str>, Rc<str> and Arc<str> depending on the use case. So for example with a *PO query, the P and O terms are only created once (couldn't reuse the input terms directly as I didn't manage to convert them to a format that the compiler accepted) and then they are cloned for each triple in the result. However this isn't done for the queries with given subject yet because they are all handled by the same iterator.

Referencing resources directly from within HDT with an &str isn't possible however because HDT is a compressed format and it's dictionary contains the strings in front coded form, so first the block needs to be located and then location in the block and then the string needs to be merged from to byte array slices and converted to unicode. I think for this reason it cannot be as fast as a Sophia fast graph, which as far as I understand it contains everything full indexed and uncompressed and ready to access.

**Comment by KonradHoeffner** [comment]
> Regarding performances, it is very interesting to have "raw" hdt-rs in the figures as well. I'll try to find some time to review your code, especially to try to understand what creates the gap between hdt-rs and sophia_hdt in some cases...

Thanks! I think a good starting point would be the triples_with_po function in https://github.com/KonradHoeffner/hdt/blob/main/src/hdt_graph.rs that answers the first query of the benchmark:

```rust
/// An iterator visiting all triples with the given predicate and object.
    fn triples_with_po<'s, TP: TTerm + ?Sized, TO: TTerm + ?Sized>(
        &'s self, p: &'s TP, o: &'s TO,
    ) -> GTripleSource<'s, Self> {
        let ps = term_string(p);
        let os = term_string(o);
        let pid = self.hdt.dict.string_to_id(&ps, &IdKind::Predicate);
        let oid = self.hdt.dict.string_to_id(&os, &IdKind::Object);
        // predicate can be neither a literal nor a blank node
        let p = Term::new_iri_unchecked(ps);
        let o = auto_term(&os).unwrap();
        Box::new(
            PredicateObjectIter::new(&self.hdt.triples, pid, oid)
                .map(move |sid| -> Result<_> {
                    Ok(StreamedTriple::by_value([
                        // subject is never a literal, so we can save a lot of CPU time here by not using auto_term
                        // TODO: could subject be a blank node?
                        Term::new_iri_unchecked(self.hdt.dict.id_to_string(sid, &IdKind::Subject).unwrap()),
                        p.clone(),
                        o.clone(),
                    ]))
                })
                .filter_map(|r| r.map_err(|e| error!("{e}")).ok())
                .into_triple_source(),
        )
    }
}
```

I see three reasons for the performance difference here:
1. string matching in auto_term is very slow
2. Term::new_iri_unchecked seems to use some regular expressions as well
3.  I can't get the compiler to accept the input P and O terms as part of the output so I convert them to string and back, which has more of a relative impact when the result set is small.

To measure the performance I found perf quite useful with converting it to the Firefox profiler input.

**Comment by KonradHoeffner** [comment]
With the current version, I think the overhead is just the `IriRef::new_unchecked(MownStr::from(x))`.

**Comment by pchampin** [comment]
`IriRef::new_unchecked` only uses regular expressions in debug mode, *not* in `--release` mode.

Measuring performances in debug code is not really relevant, because debug code is not optimize, and may contain a lot of extra code (e.g. `debug_assert`) for, well... debugging purposes :)

**Comment by KonradHoeffner** [comment]
I think I always used release mode but I will measure it again.

**Comment by KonradHoeffner** [comment]
You are right, I didn't find any regular expressions anymore and the overhead seems fine now!

# Current Results

```
?PO/7 triple IDs (?, type, person)
                        time:   [118.53 ms 118.61 ms 118.93 ms]
?PO/8 str subjects (?, type, person)
                        time:   [313.49 ms 313.65 ms 314.29 ms]
?PO/9 str triples (?, type, person)
                        time:   [325.37 ms 325.42 ms 325.43 ms]
?PO/10 Sophia HDT graph triples (?, type, person)
                        time:   [356.40 ms 356.51 ms 356.96 ms]
```

## profile of the benchmark iteration ?PO/10 Sophia HDT graph triples 

```
group.bench_function("10 Sophia HDT graph triples (?, type, person)", |b| {   
        b.iter(|| graph.triples_matching(Any, Some(&type_term), Some(&person_term)).count()) 
    });

```

![Screenshot from 2023-02-22 11-08-00](https://user-images.githubusercontent.com/839577/220589315-9b65b2be-49fc-4596-95ef-ad9c6362e7a2.png)

### overhead only

![Screenshot from 2023-02-22 11-10-00](https://user-images.githubusercontent.com/839577/220589609-6e2f2af6-93d3-4627-8fc8-e2b46424203b.png)

**Comment by pchampin** [comment]
> I have been using the Sophia adapter of the hdt library in production for some time, so I think the issue is resolved :-)

Agreed, and thanks again for the awesome work you have put in this.
I just added [a mention to `hdt`](https://github.com/pchampin/sophia_rs/blob/main/README.md#third-party-crates) in Sophia's README.
