### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by rybesh** [pchampin/sophia_rs#80]
Does Sophia have a “road map” document covering what has been done so far and what is planned for future versions?

**Comment by pchampin** [comment]
We don't have a proper Roadmap document, I'm afraid. The issue list serves as a list of "future features", while the README file gives a coarse summary of the "current features". Also, this is still a side project for everyone involved, so the development of new features is not driven by a strict planning, but more by fuzzier factors, such as the need of a given feature, or the urge to procrastinate ;-)

That being said, if you have a suggestion for the structure of such a roadmap file, a PR would be welcome...

Otherwise, feel free to open specific issues related to features/functionalities that you are wondering about, or would like to be added.

**Comment by KonradHoeffner** [comment]
A lower barrier alternative to a road map document could be to add milestones, as proposed in #139.
As an example, I often structure issues into the following milestones:

1. Next release, in this case this would be "0.8". This allows everyone to see which issues are the most important (e.g. bugs) and what the progress is towards the next release (e.g. 15 of 18 issues closed).
2. "next", this includes all issues that are important to address, however not immediately prioritized but included in the release after that (e.g. 0.9).
3. "later" for issues that are identified as relevant but not that important.
4. "wontfix" for issues that are out of scope of the library or whose implementation would cause negative effects that outweigh the benefits.
